global:
  scrape_interval: 5s      # 지표 수집 주기
  evaluation_interval: 5s

scrape_configs:
  # Spring Boot 애플리케이션 지표 수집
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080'] # 로컬 IntelliJ에서 실행 중인 앱에 접속

  # Redis 지표 수집
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']